# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'testeCocoaPods' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for testeCocoaPods

  target 'testeCocoaPodsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'testeCocoaPodsUITests' do
    inherit! :search_paths
    # Pods for testing
  end
pod "ButtonProgressBar-iOS"
end
